### ISSUE TITLE
Can not find the function: zonotope 

### ISSUE THREAD

**Issue by sjcszw** [ESCL-at-UTD/ConZono#3]
Hi, I try to run the Applied Examples/Sec7_RPI_Sets.m. But a bug arises:
      Cannot find an exact (case-sensitive) match for 'zonotope'
      The closest match is: Zonotope in C:\MATLAB\R2020b\tbxmanager\toolboxes\mpt\3.2.1\all\mpt3-3_2_1\mpt\modules\geometry\sets\Zonotope.m

But based on the input variables, it's not Zonotope.

I really appreciate any help you can provide.

**Comment by VigneshRaghu** [comment]
Thanks for sharing the error code. The function "zonotope" used in the code is from the zonotope class in the CORA toolbox [https://tumcps.github.io/CORA/] which requires the center and generator matrix of a zonotope as input arguments. If you could please download and install CORA toolbox and have it's path added, then I think you would be able to run the code without errors. Hope it helps!

**Comment by sjcszw** [comment]
It works！ Thanks a lot!
